### ISSUE TITLE
Commands for build lemonadep

### ISSUE THREAD

**Issue by kijodoari** [AltairROM/android#1]
I`m trying to build for this device and build success but cant get .zip in out folder, these are the commands i have used:

-lunch lineage_lemonadep-user
-m

what are the correct commands?

**Comment by MJPollard** [comment]
Try:

```
. build/envsetup.sh
breakfast lemonadep
make altair
```

That always works for me (the first two commands are only needed once, of course).

**Comment by kijodoari** [comment]
i used that command:
`. build/envsetup.sh
lunch lineage_lemonadep-user
mka altair`
Thank you for help and your work, incredible rom
